% Heisenberg-Weyl operators
function [g] = operator_hw(d)
    g = cell(1, d^2 -1);
    if d == 2
        g{1} = [1, 0;
                0, 1];
        g{2} = [0, 1;
                1, 0];
        g{3} = [0, -1i;
                1i, 0];
        g{4} = [1, 0;
                0, -1];
    elseif d == 3
        x = (1 + 1i) / 2;
        w = exp(1i * 2 * pi / 3);
        g{1} = [1, 0, 0;
                0, 1, 0;
                0, 0, 1];
        g{2} = [0, conj(x), x;
                x, 0, conj(x);
                conj(x), x, 0];
        g{3} = [0, x, conj(x);
                conj(x), 0, x;
                x, conj(x), 0];
        g{4} = [x+conj(x), 0, 0;
                0, x*w+conj(x)*conj(w), 0;
                0, 0, x*conj(w)+conj(x)*w];
        g{5} = [0, -conj(x)*w, -x*w;
                -x*conj(w), 0, -conj(x);
                -conj(x)*conj(w), -x, 0];
        g{6} = [0, x*conj(w), conj(x)*conj(w);
                conj(x)*w, 0, x;
                x*w, conj(x), 0];
        g{7} = [x+conj(x), 0, 0;
                0, x*conj(w)+conj(x)*w, 0;
                0, 0, x*w+conj(x)*conj(w)];
        g{8} = [0, conj(x)*conj(w), x*conj(w);
                x*w, 0, conj(x);
                conj(x)*w, x, 0];
        g{9} = [0, x*w, conj(x)*w;
                conj(x)*conj(w), 0, x;
                x*conj(w), conj(x), 0];
    elseif d == 4
        x = (1 + 1i) / 2;
        g{1} = [1, 0, 0, 0;
                0, 1, 0, 0;
                0, 0, 1, 0;
                0, 0, 0, 1];
        g{2} = [0, conj(x), 0, x;
                x, 0, conj(x), 0;
                0, x, 0, conj(x);
                conj(x), 0, x, 0];
        g{3} = [0, 0, 1, 0;
                0, 0, 0, 1;
                1, 0, 0, 0;
                0, 1, 0, 0];
        g{4} = [0, x, 0, conj(x);
                conj(x), 0, x, 0;
                0, conj(x), 0, x;
                x, 0, conj(x), 0];
        g{5} = [1, 0, 0, 0;
                0, -1, 0, 0;
                0, 0, -1, 0;
                0, 0, 0, 1];
        g{6} = (1 / sqrt(2)) * [0, -1i, 0, 1;
                                1i, 0, -1, 0;
                                0, -1, 0, 1i;
                                1, 0, -1i, 0];
        g{7} = [0, 0, -1i, 0;
                0, 0, 0, 1i;
                1i, 0, 0, 0;
                0, -1i, 0, 0];
        g{8} = (1 / sqrt(2)) * [0, -1i, 0, -1;
                                1i, 0, 1, 0;
                                0, 1, 0, 1i;
                                -1, 0, -1i, 0];
        g{9} = [1, 0, 0, 0;
                0, -1, 0, 0;
                0, 0, 1, 0;
                0, 0, 0, -1];
        g{10} = [0, -x, 0, conj(x);
                -conj(x), 0, x, 0;
                0, conj(x), 0, -x;
                x, 0, -conj(x), 0];
        g{11} = [0, 0, -1, 0;
                 0, 0, 0, 1;
                 -1, 0, 0, 0;
                 0, 1, 0, 0];
        g{12} = [0, -conj(x), 0, x;
                 -x, 0, conj(x), 0;
                 0, x, 0, -conj(x);
                 conj(x), 0, -x, 0];
        g{13} = [1, 0, 0, 0;
                 0, 1, 0, 0;
                 0, 0, -1, 0;
                 0, 0, 0, -1];
        g{14} = (1 / sqrt(2)) * [0, -1, 0, -1i;
                                 -1, 0, -1i, 0;
                                 0, 1i, 0, 1;
                                 1i, 0, 1, 0];
        g{15} = [0, 0, 1i, 0;
                 0, 0, 0, 1i;
                 -1i, 0, 0, 0;
                 0, -1i, 0, 0];
        g{16} = (1 / sqrt(2)) * [0, 1, 0, -1i;
                                 1, 0, -1i, 0;
                                 0, 1i, 0, -1;
                                 1i, 0, -1, 0];
    end
end